server:
  port: 8080
spring:
  application:
    name: "franquicias-api"
  devtools:
    add-properties: false
  data:
    mongodb:
      uri: "${MONGO_DB_URI}"
      username: "${MONGO_DB_USERNAME}"
      password: "${MONGO_DB_PASSWORD}"
      cluster-url: "${MONGO_DB_CLUSTER_URL}"
      database: "${MONGO_DB_DATABASE}"
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080, *"
